version: '3.9'

services:
  api:
    build:
      context: .
      args:
        - DEV=${DEV}
    restart: always
    ports:
      - "${DJANGO_PORT}:8000"
    volumes:
      - ./app:/app
      - static-data:/vol/web
      - ./app/static:/vol/web/static
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_DB_HOST=db
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DEBUG=${DEBUG}
      - DJANGO_ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
    depends_on:
      - db

  db:
    image: bitnami/postgresql:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}

volumes:
  db-data:
  static-data:

# gunicorn api.wsgi:application --workers=4 --threads=2 --bind 0.0.0.0:8000"